language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py -q install
  - pip install pytest-cov coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; pip install sphinx; fi
script:
  - py.test tests.py --cov jsonref --cov proxytypes --cov-report term-missing
  # Docs are in python 3 format
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python -m doctest README.rst; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then sphinx-build -b doctest docs _temp; fi
after_success:
  - coveralls
