language: python
cache: pip

# Jump through some hoops to get both python 3.7 and older versions running
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "pypy"
    - python: "pypy3"

install:
  - python setup.py -q install
  - pip install coverage
  - pip install pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install sphinx; fi

script:
  - py.test tests.py --cov jsonref --cov proxytypes --cov-report term-missing
  # Docs are in python 3 format
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m doctest README.rst; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then sphinx-build -b doctest docs _temp; fi

after_success:
  - pip install coveralls
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy
    - python: pypy3
